### PR TITLE
More interactive functions, fixes

### PR DESCRIPTION
**Pull request by Fuco1**
Here's a pull request for review... We can either merge it or I can then push directly to main.

### CODE REVIEW

**Comment by magnars** [comment]
Wow, lots of great stuff here. :) Could you add a few test for the new features and fixes? Are you familiar with ecukes at all? There are a few tests to look at here, but maybe not enough. If you want, I can add some tests for these features, and you can use that as a basis for future stuff. :)

**Comment by Fuco1** [comment]
Yea, I have a couple tests for SP as well, only quite basic stuff. I'll try to cook up something. Should I throw it all in the same file?

**Comment by magnars** [comment]
If it makes sense using the same background. Otherwise, new files are fine too.

**Comment by Fuco1** [comment]
Safe to assume this is dead? :D I'm going to close this to clean up my queues.

**Pull request closed without merging**
